### ISSUE TITLE
VTM Rendering option

### ISSUE THREAD

**Issue by TacxBiker** [vti/elemntary#12]
Hi,

when I change the VTM_RENDERING option, I get an error code:

Unhandled Promise Rejection
NonError: { code: 1, stdout: <Buffer >, stderr: '' }
    at module.exports (C:/Wahoo/elemntary-win32-x64-0.5.5/resources/app/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Wahoo/elemntary-win32-x64-0.5.5/resources/app/node_modules/electron-unhandled/index.js:50:10)
    at process.<anonymous> (C:/Wahoo/elemntary-win32-x64-0.5.5/resources/app/node_modules/electron-unhandled/index.js:130:4)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

The option does seem to be activated; the check box is checked.
On the element roamv2 there is no change, so on the elemnt itself the options doesn't seem to be changed.
Next to the line "WORD OPGESLAGEN:  (in dutch) there is a spinning circle

edit: I use elementary-win32-x64-0.5.5

![image](https://github.com/vti/elemntary/assets/75673550/ab4e7c93-8d6f-4ded-bc23-fe570b8d75bb)

A little tip; to connect a wahoo roamV2 I use the same method as described for a wahoo roam and bold V1. Just enter the setting menu, press again and connect the roam.

**Comment by vti** [comment]
Could you attach the log file? It should be somewhere here %USERPROFILE%\AppData\Roaming\Elemntary\logs\elemntary.log

**Comment by TacxBiker** [comment]
[elemntary.log](https://github.com/vti/elemntary/files/11788998/elemntary.log)

**Comment by vti** [comment]
@TacxBiker  try the latest release https://github.com/vti/elemntary/releases/tag/v0.5.6

**Comment by TacxBiker** [comment]
Hi, thanks.

I don't get that error anymore. But on my roam the navigation page is the same as on the roam V1, so no panning/zooming.

![image](https://github.com/vti/elemntary/assets/75673550/ac474ddb-944f-4a2c-8a21-c135cc30d25e)

**Comment by vti** [comment]
@TacxBiker I don't have a roam2, but i think you need to select "route" first and there should be a menu.

**Comment by TacxBiker** [comment]
Hi, see screendump
![image](https://github.com/vti/elemntary/assets/75673550/5e855d95-26aa-4596-a011-2002e5293c81)

on a V2 there should be 3 dots on the lower right to access the menu:

![image](https://github.com/vti/elemntary/assets/75673550/345e575e-5d96-4f68-b06e-9113ba1d980a)

**Comment by HerrRuin** [comment]
Hello, same problem here. Lost the Pan and Zoom Funtion on Roam v2. :(
Factory Reset dosn't help. Error in Elemntary App. How do I get the function "Pan and Zoom" back????

![fehler](https://github.com/vti/elemntary/assets/6007935/9df81c76-1638-465c-9f53-fab082c59091)
![roamv2](https://github.com/vti/elemntary/assets/6007935/fe66cd92-16d4-4cc6-aa87-c3338e20d937)

**Comment by Ebe66** [comment]
Some additional info and to report that the missing pan & zoom issue has been resolved.

Additional info about the Elemntary error message: HerrRuin is stil running on windows 7. Might this be the cause of the errors?

The missing pan & zoom function was in all likelihood (needs verification) caused by enabeling both the VTM_RENDERING and MAP_PAN_ZOOM options on a device that has this functionality natively. It seems this caused the Roam 2 to "think" it is a Roam 1.
This could not be reverted by simply disabling both options again.
In the end the solution was to place an empty file without extension in the storage root folder called  cfg_BApplication_ModelOverride_ROAM_2 this forces the unit to act as a Roam 2  which in this case it is.
For completeness this filename can be used with the other models too. the options atm are:
ELEMNT
BOLT
ROAM
BOLT_2
ROAM_1_1
ROAM_2
ACE

So creating the file cfg_BApplication_ModelOverride_BOLT_2 on a bolt 1 would cause the bolt 1 to act as a bolt 2.
