### ISSUE TITLE
Werbserver starting error

### ISSUE THREAD

**Issue by Gedankenschinder** [vti/elemntary#15]
Software

Version: 1.77.3.1 (17026)
Last updated: 2024-07-11 16:59:48

Unhandled Promise Rejection
NonError: undefined
    at module.exports (C:/Users/Manu/Desktop/elemntary-win32-x64-0.5.6/resources/app/node_modules/ensure-error/index.js:14:10)
    at handleError (C:/Users/Manu/Desktop/elemntary-win32-x64-0.5.6/resources/app/node_modules/electron-unhandled/index.js:50:10)
    at process.<anonymous> (C:/Users/Manu/Desktop/elemntary-win32-x64-0.5.6/resources/app/node_modules/electron-unhandled/index.js:130:4)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:294:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

**Comment by TheCBiker** [comment]
Same. Windows and Linux version. Webserver doesn´t start.
With Elemnt Roam V1 and Windows 11 Pro or Linux Mint

**Comment by ENTESTINKSAUER** [comment]
Had the same issue, i had to ensure the WIFI on my device is enabled - after that i was able to launch the webserver.

Keep in mind, updating the FW nowadays can lead to issues: Maps/vtms are not working anymore  - afair only ace and v3 are affected by now - roam v2 with WC50-17055 is still wokring.
